configuration:
  arguments:
    checkpointSuffix: "checkpoint"

flows:
  default:
  - log: "Before the checkpoint"
  - checkpoint: "first_${checkpointSuffix}"
  - log: "After the first checkpoint"

  step1:
  - log: "Before the hghghgh checkpoint"
  - checkpoint: "second_${checkpointSuffix}"
  - log: "After the second checkpoint"
 
  onEvent:
  - log: "Received ${event}"

  onEvent2:
  - log: "${msg}"

triggers:
  - mySystem:
      # listen for "mySystem" events that have myVar=abc
      myVar: "abc"
      entryPoint: onEvent

  - mySystem:
      # using regular expressions to match the data
      myVar: "test.*"
      entryPoint: onEvent2
      # passing additional variables
      arguments:
        msg: "We got ${event}"
